/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function House(props) {
  const { nodes, materials } = useGLTF("./models/Modern_House.glb");
  return (
    <group {...props} dispose={null} scale={[0.2, 0.2, 0.2]} position={[-16,-2,70]} rotation={[0,Math.PI,0]}>
      <group position={[0.24, 0.134, 0.114]} rotation={[Math.PI / 2, 0, 0]} scale={[0.8,0.8,0.8]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WINDOW_1.geometry}
          material={materials.Glass_1}

        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WINDOW_2.geometry}
          material={materials.wire_008008136}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LOUVER.geometry}
        material={materials.Wood}
        position={[0.24, 0.234, 0.114]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.792}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WALL.geometry}
        material={materials.wire_113135006}
        position={[0.24, 0.234, 0.114]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.792}
      />
      <group
        position={[0.24, 0.234, 0.114]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.792}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROOF_1.geometry}
          material={materials.wire_177147027}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ROOF_2.geometry}
          material={materials.Concrete}
        />
      </group>
      <group
        position={[0.24, 0.234, 0.114]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.792}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOOR_1.geometry}
          material={materials.Glass_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOOR_2.geometry}
          material={materials.wire_166229229}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DOOR_3.geometry}
          material={materials.Wood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Modern_House.glb");
