/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bit(props) {
  const { nodes, materials } = useGLTF('./models/bit.glb')
  return (
    <group {...props} dispose={null} position={[49,8,32]} scale={[70,70,70]} rotation={[0,-Math.PI/2,0]}>
      <group position={[-0.062, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1.geometry}
          material={materials.b_bg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2.geometry}
          material={materials.b}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface3.geometry}
          material={materials.b_text}
          position={[0.574, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/bit.glb')



