/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BoyStatue(props) {
  const { nodes, materials } = useGLTF('./models/boyStatue.glb')
  return (
    <group {...props} dispose={null} position={[11.5,7.1,22]} rotation={[0,Math.PI,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['uploads-files-2817143-FUNKO+POP+BASE_PRINT'].geometry}
        material={nodes['uploads-files-2817143-FUNKO+POP+BASE_PRINT'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/boyStatue.glb')
