/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cctv2(props) {
  const { nodes, materials } = useGLTF("./models/cctv.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[-47.5, 17, 48]}
      scale={[0.5, 0.5, 0.5]}
      rotation={[0, (Math.PI / 3) * 2, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stretchy_thing_that_blocks_hands_the_sequel.geometry}
        material={materials["Material.003"]}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Stretchy_thing_that_blocks_hands_is_a_trilogy_now.geometry
        }
        material={materials["Material.003"]}
        position={[0.3, -1.034, -2.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.068}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stretchy_thing_that_blocks_hands.geometry}
        material={materials["Material.003"]}
        position={[0.481, -0.734, -2.248]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.181}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IR_lights.geometry}
        material={materials["IR light diode"]}
        position={[0, -0.268, 2.01]}
        rotation={[1.888, -0.002, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Panel.geometry}
        material={materials.Metal}
        position={[0, -2.4, -4.7]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt.geometry}
        material={materials["Material.002"]}
        position={[-0.499, -2.8, -4.722]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.062, 0.012, 0.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Joint.geometry}
        material={materials["Material.001"]}
        position={[0, -2.321, -0.936]}
        rotation={[-Math.PI, 0, 0]}
        scale={[1.635, 1.571, 1.571]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.IR_lights001.geometry}
        material={materials["IR light diode"]}
        position={[-0.013, -0.42, 1.96]}
        rotation={[1.888, -0.002, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Metal}
        position={[0, -1.107, -0.726]}
        rotation={[0.317, 0, 0]}
        scale={0.627}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[0, 0.028, -0.77]}
          scale={0.097}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CCTV_cover.geometry}
        material={materials["Material.001"]}
        position={[0, -0.518, 0.653]}
        rotation={[1.888, 0, 0]}
      />
      <group
        position={[0, -0.518, 0.653]}
        rotation={[1.888, 0, 0]}
        scale={0.952}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bool_2.geometry}
          material={nodes.Bool_2.material}
          position={[-0.63, -2.856, -0.525]}
          scale={[0.038, 0.061, 0.038]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Camera.geometry}
        material={materials.circle4179}
        position={[0, -0.9, 1.819]}
        rotation={[1.888, 0, 0]}
        scale={0.422}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt007.geometry}
        material={materials["Material.002"]}
        position={[-0.6, -0.15, -2.101]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.032, -0.006, -0.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt006.geometry}
        material={materials["Material.002"]}
        position={[0, 0.15, -2.101]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.032, -0.006, -0.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt005.geometry}
        material={materials["Material.002"]}
        position={[0.6, -0.15, -2.101]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-0.032, -0.006, -0.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt003.geometry}
        material={materials["Material.002"]}
        position={[-0.599, -1.5, -4.722]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.062, 0.012, 0.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolt002.geometry}
        material={materials["Material.002"]}
        position={[0.601, -1.5, -4.722]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.062, 0.012, 0.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002.geometry}
        material={materials["Material.004"]}
        position={[1.522, -0.724, -2.241]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Material.004"]}
        position={[0.117, -1.034, -2.764]}
        rotation={[Math.PI / 2, -0.967, Math.PI / 2]}
        scale={0.585}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials["Material.004"]}
        position={[0.298, -1.034, -2.764]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.585}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bar.geometry}
        material={materials.Metal}
        position={[0, -1.657, -0.936]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.202, 0.194, 0.202]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screw_bool.geometry}
        material={nodes.Screw_bool.material}
        position={[0.6, -1.5, -4.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.071, 0.157, 0.071]}
      />
    </group>
  );
}

useGLTF.preload("./models/cctv.glb");
