/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair2(props) {
  const { nodes, materials } = useGLTF("./models/chair.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={[2, 2, 2]}
      position={[47, 0, -8]}
      rotation-y={Math.PI * 0.1}
    >
      <mesh
        name="Chair"
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials.Chair}
        position={[-1, 1.243, 0]}
        scale={[0.75, 0.152, 0.75]}
      >
        <mesh
          name="BezierCurve001"
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve001.geometry}
          material={materials.Metal}
          position={[0, -1.453, -0.231]}
          rotation={[0, 1.544, 0]}
          scale={[0.85, 4.204, 0.85]}
        />
        <mesh
          name="Cube069"
          castShadow
          receiveShadow
          geometry={nodes.Cube069.geometry}
          material={materials.Chair}
          position={[1.147, 4.909, 0]}
          scale={[0.169, 5.262, 0.914]}
        />
        <group
          name="Cylinder002"
          position={[0, -1.021, 0]}
          scale={[0.234, 0.752, 0.234]}
        >
          <mesh
            name="Cylinder000"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder000.geometry}
            material={materials["Steel Black Polished"]}
          />
          <mesh
            name="Cylinder000_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder000_1.geometry}
            material={materials["Steel White"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/chair.glb");
