/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Crates2(props) {
  const { nodes, materials } = useGLTF('./models/crate2.glb')
  return (
    <group><group {...props} dispose={null} scale={10} position={[103,1,-51]} rotation={[0,Math.PI/2,0]}>
    <group position={[0, 0.15, 0.311]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Medieval box 2']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_1.geometry}
        material={materials.Rope}
      />
    </group>
    <group position={[0, 0, -0.303]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials['Medieval box 3']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048_1.geometry}
        material={materials.Rope}
      />
    </group>
    <group position={[0, 0.26, 0.029]} rotation={[0, -1.525, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={materials['Medieval box 4']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054_1.geometry}
        material={materials.Rope}
      />
    </group>
    <group position={[0, -0.014, 0.357]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials['Medieval box 5']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_1.geometry}
        material={materials.Rope}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube036.geometry}
      material={materials['Medieval box 1']}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube036_1.geometry}
      material={materials.Rope}
    />
  </group><group {...props} dispose={null} scale={10} position={[112,3,0]}>
      <group position={[0, 0.15, 0.311]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials['Medieval box 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042_1.geometry}
          material={materials.Rope}
        />
      </group>
      <group position={[0, 0, -0.303]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials['Medieval box 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_1.geometry}
          material={materials.Rope}
        />
      </group>
      <group position={[0, 0.26, 0.029]} rotation={[0, -1.525, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={materials['Medieval box 4']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_1.geometry}
          material={materials.Rope}
        />
      </group>
      <group position={[0, -0.014, 0.357]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062.geometry}
          material={materials['Medieval box 5']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_1.geometry}
          material={materials.Rope}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials['Medieval box 1']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036_1.geometry}
        material={materials.Rope}
      />
    </group></group>
  )
}

useGLTF.preload('./models/crate2.glb')
