/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Crate(props) {
  const { nodes, materials } = useGLTF('./models/crate.glb')
  return (
    <group>
        <group {...props} dispose={null} scale={5} position={[33,-16,35]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube626.geometry}
        material={materials['Material.001']}
        position={[4.859, 3.806, 4.283]}
        scale={0.408}
      />
    </group>
    <group {...props} dispose={null} scale={5} position={[33,-13,35]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube626.geometry}
        material={materials['Material.001']}
        position={[4.859, 3.806, 4.283]}
        scale={0.408}
      />
    </group>
    </group>
  )
}

useGLTF.preload('./models/crate.glb')
