/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Frames(props) {
  const { nodes, materials } = useGLTF('./models/frames.glb')
  return (
    <group
      {...props}
      dispose={null}
      position={[0, 13, -49.5]}
      scale={4}
      rotation={[0, Math.PI / 2*-1, 0]}
    >
      <group rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 0.717]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_3.geometry}
          material={materials.photo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.glass}
          position={[0, 0.026, 0]}
          scale={[0.901, 0.901, 0.861]}
        />
      </group>
      <group
        position={[0, 0.465, -1.438]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.607, 0.982, 0.436]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_3.geometry}
          material={materials["photo.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials.glass}
          position={[-0.001, 0.026, -0.013]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.807, 0.739, 0.82]}
        />
      </group>
      <group
        position={[0, 0.465, 1.436]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.607, 0.982, 0.436]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_3.geometry}
          material={materials["photo.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.glass}
          position={[-0.013, 0.026, -0.013]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.807, 0.739, 0.82]}
        />
      </group>
      <group
        position={[0, -0.468, -1.438]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.607, 0.982, 0.436]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_3.geometry}
          material={materials["photo.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.glass}
          position={[-0.001, 0.026, -0.013]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.807, 0.739, 0.82]}
        />
      </group>
      <group
        position={[0, -0.468, 1.436]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.607, 0.982, 0.436]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_3.geometry}
          material={materials["photo.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials.glass}
          position={[-0.013, 0.026, -0.013]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.807, 0.739, 0.82]}
        />
      </group>
      <group
        position={[0, 0, -2.679]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.741, 0.979, 0.532]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_3.geometry}
          material={materials["photo.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials.glass}
          position={[0, 0.026, -0.004]}
          scale={[0.879, 0.666, 0.841]}
        />
      </group>
      <group
        position={[0, 0, 2.679]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.741, 0.979, 0.532]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_3.geometry}
          material={materials["photo.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials.glass}
          position={[0, 0.026, 0.023]}
          scale={[0.879, 0.666, 0.841]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./models/frames.glb')
