/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function GlassDoor(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/glassDoor.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group rotation={[0, Math.PI * 0.5, 0]}>
      <group
        ref={group}
        {...props}
        dispose={null}
        position={[-153.4, 0, 62.3]}
        rotation={[0, 0, 0]}
        scale={25}
      >
        <group name="Scene">
          <mesh
            name="Object010"
            castShadow
            receiveShadow
            geometry={nodes.Object010.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object011"
            castShadow
            receiveShadow
            geometry={nodes.Object011.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object012"
            castShadow
            receiveShadow
            geometry={nodes.Object012.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object013"
            castShadow
            receiveShadow
            geometry={nodes.Object013.geometry}
            material={materials.wire_115115115}
            position={[-0.005, 0, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object014"
            castShadow
            receiveShadow
            geometry={nodes.Object014.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object015"
            castShadow
            receiveShadow
            geometry={nodes.Object015.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object016"
            castShadow
            receiveShadow
            geometry={nodes.Object016.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="Object017"
            castShadow
            receiveShadow
            geometry={nodes.Object017.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
          <mesh
            name="SlidingWindow002"
            castShadow
            receiveShadow
            geometry={nodes.SlidingWindow002.geometry}
            material={materials.wire_115115115}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/glassDoor.glb");
