/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HeadphoneStand3(props) {
  const { nodes, materials } = useGLTF('./models/headphoneStand.glb')
  return (
    <group {...props} dispose={null} scale={[4,4,5]} position={[3,3.5,19]} rotation={[0,Math.PI/2,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб.geometry}
        material={materials.Матеріал}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб001.geometry}
        material={materials.Матеріал}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб002_Куб003.geometry}
        material={materials['Матеріал.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб003_Куб004.geometry}
        material={materials.Матеріал}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб004_Куб005.geometry}
        material={materials.Матеріал}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб005_Куб006.geometry}
        material={materials['Матеріал.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб006_Куб007.geometry}
        material={materials['Матеріал.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб007_Куб008.geometry}
        material={materials['Матеріал.003']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб008_Куб009.geometry}
        material={materials['Матеріал.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Куб009_Куб010.geometry}
        material={materials['Матеріал.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Сфера.geometry}
        material={materials['Матеріал.003']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Сфера001.geometry}
        material={materials['Матеріал.003']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.122}
      />
    </group>
  )
}

useGLTF.preload('./models/headphoneStand.glb')
