/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HelpDesk(props) {
  const { nodes, materials } = useGLTF('./models/helpDesk.glb')
  return (
    <group {...props} dispose={null} scale={[2.3,2.3,2.3]} rotation-y={Math.PI * 3.4} position={[38,0,38]}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.054}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_1'].geometry}
          material={materials.wire_087224198}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_2'].geometry}
          material={materials.wire_134110008}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_3'].geometry}
          material={materials.wire_224086086}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_4'].geometry}
          material={materials.wire_028089177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_5'].geometry}
          material={materials.wire_177028149}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_6'].geometry}
          material={materials.wire_229166215}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_7'].geometry}
          material={materials.wire_006134006}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_8'].geometry}
          material={materials.wire_224198087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_9'].geometry}
          material={materials.wire_143224087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d-model_10'].geometry}
          material={materials.wire_134006006}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/helpDesk.glb')
