/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lamp2(props) {
  const { nodes, materials } = useGLTF('./models/lamp.glb')
  return (
    <><group {...props} dispose={null} scale={[10,10,10]} rotation={[0,Math.PI*1.5,0]} position={[-51.5,9,20]}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Box02.geometry}
      material={materials['Material.001']}
      rotation={[Math.PI / 2, 0, 0]}
    />
  </group></>
  )
}

useGLTF.preload('./models/lamp.glb')
