/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pc(props) {
  const { nodes, materials } = useGLTF('./models/pc.glb')
  return (
    <group {...props} dispose={null} scale={[9,9,9]} position={[38,8,-5]} rotation-y={Math.PI * 0.3}>
      <group position={[0.228, 0, 0.056]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.imac_1.geometry}
          material={materials['case']}
        />
        <mesh castShadow receiveShadow geometry={nodes.imac_2.geometry} material={materials.pied} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.imac_3.geometry}
          material={materials.Couvercle_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.imac_4.geometry}
          material={materials.Couvercle_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.imac_5.geometry}
          material={materials.ecrand_image}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.imac_6.geometry}
          material={materials.ecrandcintour}
        />
      </group>
      <group position={[0, 0, 0.413]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.clavier_imac_1.geometry}
          material={materials.touche}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.clavier_imac_2.geometry}
          material={materials.base_clavier}
        />
      </group>
      <group position={[0.319, 0, 0.329]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mouse_imac_1.geometry}
          material={materials.botton}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mouse_imac_2.geometry}
          material={materials.mouse}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mouse_imac_3.geometry}
          material={materials.dessous}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/pc.glb')
