/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PhoneBox(props) {
  const { nodes, materials } = useGLTF("./models/phoneBox.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[-18.5, 5.7, -20]}
      rotation={[(Math.PI / 2) * 3, 0, 0]}
      scale={10}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FrontBox.geometry}
        material={materials.Box}
        position={[0.053, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/phoneBox.glb");
