/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PSLogo(props) {
  const { nodes, materials } = useGLTF('./models/pslogo.glb')
  return (
    <group {...props} dispose={null} scale={[2,2,2]} position={[-24.5,5,23.5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.xo.geometry}
        material={materials.set1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.219}
      />
    </group>
  )
}

useGLTF.preload('./models/pslogo.glb')



