/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rickshaw(props) {
  const { nodes, materials } = useGLTF('./models/rickshaw.glb')
  return (
    <group {...props} dispose={null} scale={5} rotation={[0,Math.PI*0.5,0]} position={[-80,1.7,-20]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube227.geometry}
        material={materials['Material.017']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder166.geometry}
        material={materials['Material.009']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube228.geometry}
        material={materials['Material.012']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <group position={[0.921, 1.189, 0.002]} scale={[1.074, 1.074, 0.996]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube207.geometry}
          material={materials['RED LIGHT']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube207_1.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube230.geometry}
        material={materials['BLACK RUBBER']}
        position={[-0.004, 0.023, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[-0.176, 0.032, 0.002]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.076, 0.082, 0.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={materials['SHINY METAL']}
        position={[1.13, 0.869, 0.002]}
        rotation={[Math.PI / 2, -0.178, -Math.PI / 2]}
        scale={[0.008, 0.004, 0.009]}
      />
      <group position={[0.903, 0.908, 0.002]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 1.008]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder113.geometry}
          material={materials['HEAD LIGHT']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder113_1.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder168.geometry}
        material={materials['Material.001']}
        position={[-0.06, 1.206, 0.058]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.774, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube231.geometry}
        material={materials['Material.002']}
        position={[0.036, 0.802, 0.003]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder169.geometry}
        material={materials['Material.001']}
        position={[0.424, 0.563, 0.002]}
        scale={[0.012, 0.232, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder170.geometry}
        material={materials['Material.018']}
        position={[1.27, 0.253, 0.002]}
        rotation={[Math.PI / 2, -0.022, 0]}
        scale={[1, 0.658, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube232.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.004, 0.079, 0.002]}
        rotation={[0, 0, -0.026]}
        scale={[1, 0.769, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder171.geometry}
        material={materials['BLACK RUBBER.002']}
        position={[1.268, 0.26, 0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 0.803, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder172.geometry}
        material={materials['SHINY METAL']}
        position={[1.268, 0.258, 0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.935, 0.751, 0.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder173.geometry}
        material={materials['SHINY METAL']}
        position={[1.268, 0.26, 0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.935, 0.751, 0.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials['BLACK RUBBER.005']}
        position={[0.961, 0.322, 0.002]}
        rotation={[-Math.PI, 0, 1.811]}
        scale={[-0.169, -0.191, -0.141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube233.geometry}
        material={materials['Material.002']}
        position={[-0.74, 0.829, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube234.geometry}
        material={materials['Material.002']}
        position={[-1.062, 1.058, 0.002]}
        rotation={[0, 0, -1.449]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube235.geometry}
        material={materials['LEATHER TRIM']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube236.geometry}
        material={materials['Material.015']}
        position={[-0.114, -0.084, 0.002]}
        rotation={[0, 0, -0.076]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube237.geometry}
        material={materials['Material.002']}
        position={[-0.022, 1.462, 0.003]}
        rotation={[0, 0, -1.658]}
        scale={[1.082, 1.001, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder174.geometry}
        material={materials.SCREWS}
        position={[-1.286, 1.11, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 0.927, 1]}
      />
      <group position={[0.002, 0.031, 0.002]} rotation={[0, 0, 0.015]} scale={[1, 1, 0.927]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube215.geometry}
          material={materials['BLACK RUBBER']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube215_1.geometry}
          material={materials['SCREWS.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube239.geometry}
        material={materials['BLACK RUBBER']}
        position={[-0.018, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve063.geometry}
        material={materials['BLACK RUBBER']}
        position={[1.035, 0.901, -0.059]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube240.geometry}
        material={materials['Material.014']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <group position={[-0.014, 0.032, 0.003]} scale={[1, 1, 0.927]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube218.geometry}
          material={materials['SCREWS.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube218_1.geometry}
          material={materials['Material.010']}
        />
      </group>
      <group
        position={[0.869, 1.192, 0.003]}
        rotation={[0, 0, -0.086]}
        scale={[0.032, 0.032, 0.029]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube219.geometry}
          material={materials['SCREWS.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube219_1.geometry}
          material={materials['BLACK RUBBER.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube219_2.geometry}
          material={materials['SCREWS.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve064.geometry}
        material={materials['BLACK RUBBER']}
        position={[1.035, 0.901, -0.09]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <group position={[0.95, 1.106, -0.153]} scale={[0.017, 0.017, 0.016]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder121.geometry}
          material={materials['BLACK RUBBER']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder121_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[0.95, 1.106, -0.197]} scale={[0.017, 0.017, 0.016]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder121.geometry}
          material={materials['BLACK RUBBER']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder121_1.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[0.806, 1.104, 0.586]} scale={[0.009, 0.009, 0.008]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder122.geometry}
          material={materials['BLACK RUBBER']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder122_1.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube243.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.932, 1.102, -0.34]}
        rotation={[0, 0.511, 0]}
        scale={[0.034, 0.042, 0.039]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder178.geometry}
        material={materials.SCREWS}
        position={[0.888, 1.146, -0.354]}
        rotation={[0, 0.211, 0]}
        scale={[-0.003, -0.004, -0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube244.geometry}
        material={materials['Material.006']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder179.geometry}
        material={materials['BLACK RUBBER.002']}
        position={[-1.094, 0.312, 0.609]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.166, 0.936, 1.166]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder180.geometry}
        material={materials['SHINY METAL']}
        position={[-1.094, 0.312, 0.609]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.091, 0.875, 1.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder181.geometry}
        material={materials['SHINY METAL']}
        position={[-1.094, 0.312, 0.609]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.091, 0.875, 1.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder182.geometry}
        material={materials['BLACK RUBBER.002']}
        position={[-1.094, 0.312, -0.606]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.166, 0.936, 1.166]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder183.geometry}
        material={materials['SHINY METAL']}
        position={[-1.094, 0.312, -0.606]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.091, 0.875, 1.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder184.geometry}
        material={materials['SHINY METAL']}
        position={[-1.094, 0.312, -0.606]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.091, 0.875, 1.091]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve065.geometry}
        material={materials['BLACK RUBBER']}
        position={[1.035, 0.901, -0.177]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube245.geometry}
        material={materials.COVER}
        position={[-0.133, 1.791, 0.664]}
        scale={[0.017, 0.023, 0.016]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube246.geometry}
        material={materials['Material.013']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube247.geometry}
        material={materials['SCREWS.002']}
        position={[0.932, 1.102, -0.34]}
        rotation={[0, 0.511, 0]}
        scale={[0.034, 0.042, 0.039]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube248.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.002, 0.031, 0.002]}
        rotation={[0, 0, 0.015]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube249.geometry}
        material={materials['BLACK RUBBER']}
        position={[-0.029, 0.031, 0.002]}
        rotation={[0, 0, 0.015]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube250.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.002, 0.026, 0.002]}
        rotation={[0, 0, 0.015]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube251.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.002, 0.031, 0.002]}
        rotation={[0, 0, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube252.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.002, 0.031, 0.002]}
        rotation={[0, 0, 0.015]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve066.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.878, 1.252, 0.07]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve067.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.871, 1.255, 0.106]}
        rotation={[0.108, -0.001, -1.551]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve068.geometry}
        material={materials['Material.004']}
        position={[0.899, 1.26, 0.085]}
        rotation={[0.108, -0.001, -1.551]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube253.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.797, 1.085, -0.145]}
        rotation={[-0.019, 0.044, 0.407]}
        scale={[0.03, 0.008, 0.03]}
      />
      <group
        position={[0.797, 1.087, -0.145]}
        rotation={[-0.019, 0.044, 0.407]}
        scale={[0.03, 0.008, 0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube231_1.geometry}
          material={materials['SCREWS.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube231_2.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube255.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.923, 1.092, 0.314]}
        rotation={[0, -0.463, 0]}
        scale={[0.053, 0.066, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder185.geometry}
        material={materials.SCREWS}
        position={[0.903, 1.16, 0.244]}
        rotation={[0, -0.763, 0]}
        scale={[-0.005, -0.007, -0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube256.geometry}
        material={materials['SCREWS.002']}
        position={[0.923, 1.092, 0.314]}
        rotation={[0, -0.463, 0]}
        scale={[0.053, 0.066, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve069.geometry}
        material={materials['Material.004']}
        position={[1.031, 0.908, -0.141]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve070.geometry}
        material={materials['Material.004']}
        position={[1.031, 0.916, -0.125]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.087, 0.087, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube257.geometry}
        material={materials['Prism Glass with absorbtion.001']}
        position={[-0.046, 0.03, 0.003]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube258.geometry}
        material={materials['BLACK RUBBER']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve071.geometry}
        material={materials['BLACK RUBBER']}
        position={[0.935, 0.882, 0.269]}
        rotation={[-0.321, -0.17, -1.142]}
        scale={[0.06, 0.06, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials.Material}
        position={[1.15, 1.131, 0.013]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <group position={[0.715, 1.448, 0.685]} rotation={[Math.PI / 2, 0.056, 0]} scale={1.859}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder124.geometry}
          material={materials['BLACK RUBBER.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder124_1.geometry}
          material={materials['Material.007']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder188.geometry}
        material={materials['BLACK RUBBER.006']}
        position={[1.082, 1.218, 0.019]}
        rotation={[1.338, 0.233, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube259.geometry}
        material={materials['BLACK RUBBER.002']}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube260.geometry}
        material={materials['Material.008']}
        position={[-0.006, 0.015, 0.005]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube261.geometry}
        material={materials.Material}
        position={[0, 0.015, 0.002]}
        scale={[1, 1, 0.927]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube262.geometry}
        material={materials['Material.016']}
        position={[-0.029, 0.015, 0.002]}
        scale={[1, 1, 0.95]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle021.geometry}
        material={nodes.Circle021.material}
        position={[1.268, 0.258, 0.034]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.029}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle022.geometry}
        material={materials['BLACK RUBBER.007']}
        position={[1.29, 0.255, 0.111]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle023.geometry}
        material={materials['SCREWS.006']}
        position={[1.341, 0.255, 0.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.232}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle024.geometry}
        material={materials['SCREWS.006']}
        position={[1.267, 0.255, 0.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.232}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle025.geometry}
        material={materials['SCREWS.006']}
        position={[1.198, 0.255, 0.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.232}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder189.geometry}
        material={materials['SCREWS.001']}
        position={[1.35, 0.376, 0.082]}
        scale={1.167}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={materials['SCREWS.007']}
        position={[1.274, 0.28, 0.079]}
        scale={-0.022}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder190.geometry}
        material={materials['SCREWS.001']}
        position={[1.209, 0.412, 0.082]}
        scale={1.476}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve072.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[1.259, 0.225, 0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle026.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[1.259, 0.225, 0.072]}
        scale={0.02}
      />
      <group
        position={[-1.527, 0.785, 0.194]}
        rotation={[Math.PI / 2, 0.059, Math.PI / 2]}
        scale={0.124}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Screenshot_2023-08-11_at_1120007_1'].geometry}
          material={materials['Screenshot 2023-08-11 at 11.20.58']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Screenshot_2023-08-11_at_1120007_2'].geometry}
          material={materials['Screenshot 2023-08-11 at 11.20.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Screenshot_2023-08-11_at_1120007'].geometry}
        material={materials['Screenshot 2023-08-11 at 11.20.001']}
        position={[-1.519, 0.786, 0.194]}
        rotation={[Math.PI / 2, 0.127, Math.PI / 2]}
        scale={0.124}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials['Material.001']}
        position={[-0.176, 0.032, 0.002]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.076, 0.082, 0.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[-1.119, 0.415, 0.422]}
        rotation={[-Math.PI / 2, 0.272, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder191.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[-1.292, 0.273, -0.006]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle027.geometry}
        material={materials['BLACK RUBBER.004']}
        position={[-1.448, 0.266, -0.103]}
        scale={0.149}
      />
    </group>
  )
}

useGLTF.preload('./models/rickshaw.glb')
