/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Road(props) {
  const { nodes, materials } = useGLTF("./models/road.glb");
  return (
    <group>
         <group
        {...props}
        dispose={null}
        position={[15, 1, -67.8]}
        scale={[15, 15, 15]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
        <group
        {...props}
        dispose={null}
        position={[-53.1, 1, -67.8]}
        scale={[15, 15, 15]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
        <group
        {...props}
        dispose={null}
        position={[-73.6, 1.2, -47.4]}
        scale={[15, 15, 15]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group
        {...props}
        dispose={null}
        position={[-73.6, 1.2, 20.7]}
        scale={[15, 15, 15]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group
        {...props}
        dispose={null}
        position={[-53.1, 1, 67.5]}
        scale={[15, 15, 15]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group
        {...props}
        dispose={null}
        position={[15, 1, 67.5]}
        scale={[15, 15, 15]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <group
          position={[0, 0, -1.053]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <group
          position={[0, 0, 1.208]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.824, -0.038, -1.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/road.glb");
