
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Samsung(props) {
  const { nodes, materials } = useGLTF('./models/samsung2.glb')
  return (
    <group {...props} dispose={null} scale={[5,5,1]} rotation={[0,-Math.PI/2,0]} position={[50,7.5,-22]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.001']}
        position={[0.034, 0.3, 1.276]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.524}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.002']}
        position={[0.034, 0.458, 1.221]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/samsung2.glb')





