/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF ,Text} from '@react-three/drei'

export function Sign(props) {
  const { nodes, materials } = useGLTF('./models/sign.glb')
  return (
    <group {...props} dispose={null} scale={2.5}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.19}
      />
      {/* Adding a mesh with text */}
  <Text
    position={[-0.1, 4.4, 2.1]}
    rotation={[0, -Math.PI/2, 0]}   
    fontSize={0.5}         
    color="black"          
    anchorX="center"       
    anchorY="middle"       
  >Phones</Text>
  <Text
    position={[0.1, 4.4, 2.1]}
    rotation={[0, Math.PI/2, 0]}   
    fontSize={0.5}         
    color="black"          
    anchorX="center"       
    anchorY="middle"       
  >Phones</Text>
    </group>
  )
}

useGLTF.preload('./models/sign.glb')
