/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sofa3(props) {
  const { nodes, materials } = useGLTF('./models/sofa.glb')
  return (
    <group {...props} dispose={null} scale={[10,10,10]} position={[-30,2,-45]}>
      <group name="Scene">
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[0.932, -0.073, -0.372]}
          rotation={[-Math.PI, 0, -0.175]}
          scale={[0.019, 0.092, 0.018]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-0.932, -0.073, 0.365]}
          rotation={[0, 0, -0.175]}
          scale={[0.019, 0.092, 0.018]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={nodes.Cube009.material}
          position={[0.003, 0.406, -0.158]}
          rotation={[-0.092, 0, 0]}
          scale={[0.295, 0.175, 0.071]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube008"
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[0.556, 0.406, -0.158]}
          rotation={[-0.092, 0, 0]}
          scale={[0.261, 0.175, 0.071]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[-0.553, 0.406, -0.158]}
          rotation={[-0.092, 0, 0]}
          scale={[0.261, 0.175, 0.071]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[0.001, 0.204, 0.102]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.277, -0.042, -0.334]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[0.553, 0.202, 0.103]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.269, -0.042, -0.334]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-0.554, 0.202, 0.103]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.269, -0.042, -0.334]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[-0.909, 0.229, 0.008]}
          scale={[0.09, 0.181, 0.421]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[0.003, 0.269, -0.322]}
          rotation={[0, 1.571, 0]}
          scale={[0.09, 0.21, 0.824]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[0.912, 0.229, 0.008]}
          scale={[0.09, 0.181, 0.421]}
          material-transparent={false}
          material-opacity={1}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material-transparent={false}
          material-opacity={1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/sofa.glb')
