/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Speaker4(props) {
  const { nodes, materials } = useGLTF('./models/speaker2.glb')
  return (
    <group {...props} dispose={null} scale={[0.8,0.8,0.8]} rotation={[0,Math.PI/2,0]} position={[-27,10.5,49]}>
      <group position={[0.589, 1.282, 0.017]} scale={[0.757, 0.786, 0.786]} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_3.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_4.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_5.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_6.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_7.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Back_hole002.geometry}
          material={materials['Material.010']}
          position={[-0.779, -1.631, -0.021]}
          scale={[1.322, 1.272, 1.272]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Backplate.geometry}
          material={materials['Material.018']}
          position={[-2.089, -1.631, -0.021]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[1.201, 1.248, 1.201]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_plate.geometry}
          material={materials['Material.017']}
          position={[0.066, -3.001, 0.927]}
          scale={[0.143, 0.012, 0.137]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_plate001.geometry}
          material={materials['Material.017']}
          position={[0.066, -3.001, -0.988]}
          scale={[0.143, 0.012, 0.137]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_plate002.geometry}
          material={materials['Material.017']}
          position={[-1.849, -3.001, -0.988]}
          scale={[0.143, 0.012, 0.137]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_plate003.geometry}
          material={materials['Material.017']}
          position={[-1.832, -3.001, 0.927]}
          scale={[0.143, 0.012, 0.137]}
        />
        <group
          position={[-2.115, -1.039, -0.03]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.081, 0.084, 0.081]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_1.geometry}
            material={materials['Material.012']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.JBL_plate.geometry}
          material={materials['Material.007']}
          position={[0.495, -2.788, -0.021]}
          scale={[0.132, 0.127, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LEd.geometry}
          material={materials['Material.019']}
          position={[0.494, -0.52, -0.021]}
          scale={[0.014, 0.014, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.On_off.geometry}
          material={materials['Material.013']}
          position={[-2.186, -2.094, 1.253]}
          scale={[0.372, 0.358, 0.358]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere003.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.633, -0.394]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004.geometry}
          material={materials['Material.009']}
          position={[-2.091, -0.163, -0.001]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere006.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.643, 0.351]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere007.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.168, -1.09]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere008.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.168, 1.056]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere009.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.966, 0.682]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere010.geometry}
          material={materials['Material.009']}
          position={[-2.091, 0.966, -0.747]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere011.geometry}
          material={materials['Material.009']}
          position={[-2.091, -2.65, -0.726]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere012.geometry}
          material={materials['Material.009']}
          position={[-2.091, -2.656, 0.682]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere013.geometry}
          material={materials['Material.009']}
          position={[-2.091, -1.936, -1.09]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere014.geometry}
          material={materials['Material.009']}
          position={[-2.091, -1.941, 1.061]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.037, 0.039, 0.037]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere015.geometry}
          material={materials['Material.009']}
          position={[0.476, -2.34, 0.632]}
          rotation={[0.001, 0.248, -1.299]}
          scale={[0.052, 0.053, 0.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere016.geometry}
          material={materials['Material.009']}
          position={[-1.137, -2.34, -0.036]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.051, 0.054, 0.051]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere017.geometry}
          material={materials['Material.009']}
          position={[0.472, -0.931, 0.632]}
          rotation={[-1.576, 0.288, -1.317]}
          scale={[0.052, 0.053, 0.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere018.geometry}
          material={materials['Material.009']}
          position={[0.476, -0.932, -0.678]}
          rotation={[2.95, 0.247, -1.298]}
          scale={[0.052, 0.053, 0.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere019.geometry}
          material={materials['Material.009']}
          position={[0.477, -2.344, -0.678]}
          rotation={[1.449, 0.251, -1.303]}
          scale={[0.052, 0.053, 0.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere021.geometry}
          material={materials['Material.009']}
          position={[-2.103, -0.163, -0.001]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere022.geometry}
          material={materials['Material.009']}
          position={[-2.091, -0.945, -0.594]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere023.geometry}
          material={materials['Material.009']}
          position={[-2.091, -1.22, -0.311]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere024.geometry}
          material={materials['Material.009']}
          position={[-2.091, -0.706, -0.723]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere025.geometry}
          material={materials['Material.009']}
          position={[-2.091, -0.719, 0.771]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.038, 0.04, 0.038]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere039.geometry}
          material={materials['Material.009']}
          position={[-0.922, -2.34, -0.241]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.051, 0.054, 0.051]}
        />
        <group position={[-2.003, -2.119, -0.429]} scale={[1.3, 1.309, 1.251]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials['Material.012']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Switch.geometry}
          material={materials['Material.004']}
          position={[-2.08, -1.352, -0.098]}
          scale={[0.017, 0.016, 0.016]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Switch001.geometry}
          material={materials['Material.004']}
          position={[-2.022, -0.948, 0.58]}
          scale={[0.028, 0.027, 0.027]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Switch002.geometry}
          material={materials['Material.004']}
          position={[-2.08, -1.355, 0.242]}
          scale={[0.017, 0.016, 0.016]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Volume_Knob.geometry}
          material={materials['Material.011']}
          position={[-2.185, -1.494, 0.477]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-0.095, -0.099, -0.095]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Xlr.geometry}
          material={materials['Material.004']}
          position={[-1.968, -1.075, -0.448]}
          rotation={[0, -1.571, 0]}
          scale={[0.142, 0.142, 0.147]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/speaker2.glb')
