/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Speaker2(props) {
  const { nodes, materials } = useGLTF('./models/speaker.glb')
  return (
    <group {...props} dispose={null} scale={[8,8,10]} rotation={[0,Math.PI/2,0]} position={[-12.5,4.5,45]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsCircle003.geometry}
        material={materials.Tower}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsCircle003_1.geometry}
        material={materials.Tower2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsCircle003_2.geometry}
        material={materials.Speakers}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsCircle003_3.geometry}
        material={materials['Speakers.001']}
      />
    </group>
  )
}

useGLTF.preload('./models/speaker.glb')
