/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TrafficLight(props) {
  const { nodes, materials } = useGLTF("./models/trafficLight.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[-60, 0, 53]}
      rotation={[0, Math.PI/2*-1, 0]}
      scale={1.5}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Цилиндр003.geometry}
        material={materials["Материал.006"]}
        position={[0, 11.911, 0]}
        scale={[0.31, 0.272, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Плоскость.geometry}
        material={materials["Материал.007"]}
        position={[-0.688, 15.138, 9.548]}
        scale={[0.308, 0.657, 0.657]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Цилиндр004.geometry}
        material={materials["Материал.001"]}
        position={[-0.463, 15.074, 9.559]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.445, 0.175, 0.445]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Цилиндр005.geometry}
        material={materials["Материал.002"]}
        position={[-0.501, 14.027, 9.559]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.445, 0.175, 0.445]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Цилиндр006.geometry}
        material={materials["Материал.003"]}
        position={[-0.501, 12.965, 9.559]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.445, 0.175, 0.445]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Плоскость001.geometry}
        material={nodes.Плоскость001.material}
        position={[-0.688, 14.086, 9.548]}
        scale={[0.308, 0.657, 0.657]}
      />
    </group>
  );
}

useGLTF.preload("./models/trafficLight.glb");
