/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TvStand(props) {
  const { nodes, materials } = useGLTF('./models/tvStand.glb')
  return (
    <group {...props} dispose={null} scale={[15,12,12]} rotation-y={Math.PI * 0.5} position={[0,0.3,50]}>
      
      <group position={[0.465, 0.122, 0.25]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box012.geometry}
          material={materials.плинтуса}
          position={[-0.909, 2.422, -0.144]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box022.geometry}
          material={materials.Ручки}
          position={[-1.183, 2.154, -0.227]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      <group position={[0.293, 0.122, -0.345]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box011.geometry}
          material={materials.плинтуса}
          position={[6.102, 2.422, -0.182]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box023.geometry}
          material={materials.Ручки}
          position={[6.496, 2.154, -0.078]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      <group position={[0.479, 0.181, -0.946]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box010.geometry}
          material={materials.плинтуса}
          position={[-1.181, 0.12, 1.422]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box024.geometry}
          material={materials.Ручки}
          position={[-1.181, 0.294, 10.28]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
      </group>
      <group position={[0.237, 0.166, -0.946]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box004.geometry}
          material={materials.плинтуса}
          position={[-8.268, 0.641, -22.8]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials.Ручки}
          position={[-6.071, -6.314, 9.966]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={materials.Ручки}
          position={[6.609, -6.314, 9.966]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials.Ручки}
          position={[-6.071, -6.314, -8.936]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials.Ручки}
          position={[6.609, -6.314, -8.936]}
          rotation={[Math.PI, 0, 0]}
        />
      </group>
      <group position={[0.247, 0.166, -0.048]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box003.geometry}
          material={materials.плинтуса}
          position={[-8.661, 9.844, -12.097]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.Ручки}
          position={[-6.465, -6.322, 21.081]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.Ручки}
          position={[6.215, -6.322, 21.081]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.Ручки}
          position={[-6.465, -6.322, -20.941]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials.Ручки}
          position={[6.215, -6.322, -20.941]}
          rotation={[Math.PI, 0, 0]}
        />
      </group>
      <group position={[0.237, 0.285, 1.12]} scale={[0.025,0.025,0.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box005.geometry}
          material={materials.плинтуса}
          position={[-8.268, 5.195, -23.889]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.Ручки}
          position={[-6.071, -11.012, 9.461]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.Ручки}
          position={[6.609, -11.012, 9.461]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.Ручки}
          position={[-6.071, -11.012, -9.303]}
          rotation={[Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials.Ручки}
          position={[6.609, -11.012, -9.303]}
          rotation={[Math.PI, 0, 0]}
        />
      </group>
      <group position={[0.243, 0.275, -1.51]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box005001.geometry}
          material={materials.плинтуса}
          position={[-8.268, 5.195, -58.889]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[2,1,1]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/tvStand.glb')
