/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Child(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/child.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions?.praying?.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[-8,0,30]}
          rotation={[Math.PI / 2, 0, Math.PI / 5*2]}
          scale={[0.05, 0.05, 0.05]}
        >
          <skinnedMesh
            name="Ch09"
            geometry={nodes.Ch09.geometry}
            material={materials.Ch09_body}
            skeleton={nodes.Ch09.skeleton}
          />
          <primitive object={nodes.mixamorig6Hips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/child.glb");
