/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Mother(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/mother.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions?.no?.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[-15,0,32]}
          rotation={[Math.PI / 2, 0, (Math.PI / 5) * 7]}
          scale={[0.06, 0.06, 0.06]}
        >
          <skinnedMesh
            name="Peasant_girl"
            geometry={nodes.Peasant_girl.geometry}
            material={materials.Peasant_Girl}
            skeleton={nodes.Peasant_girl.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/mother.glb");
